spring:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/daonddb
    username: daond_app
    password: daondhahaha
    name: daond@postgresql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        '[show_sql]': false
        '[use_sql_comments]': true
        '[format_sql]': true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        '[globally_quoted_identifiers]': true

logging:
  level:
    ROOT: INFO
    com.github.brunoabdon: DEBUG
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.springframework.jdbc.core.JdbcTemplate: ERROR
    org.springframework.jdbc.core.StatementCreatorUtils: ERROR
    org.springframework.batch: ERROR
